### PR TITLE
 BubbleSort

### PR DESCRIPTION
**Pull request by i-Gagan**
i Explained This one

### CODE REVIEW

**Comment by i-Gagan** [comment]
@imaprincess Check this one !!

**Comment by imaprincess** [comment]
Please, make some changes, like: 
- define a class BubbleSort with a function to print the list and a function to sort the list like https://github.com/imaprincess/Algorithms-4-everyone/pull/7/files : it is more easy to understand and more beautiful to see
- Delete the part where the user inserts the numbers: if I want to sort 10024832948 numbers, I'd prefer not to insert them 😉 
- Delete the first block of comments: I don't want to steal you this code, but I'd prefer if there isn't any name at all, because if there's your name on the top of your file I can't modify it, because if I modify it it isn't yours or mine, so it would be a problem (probably I'll start soon modifying pr codes, because I'd like a big repo where all the file have the same "style")

**Comment by i-Gagan** [comment]
@imaprincess Updated the file .

**Comment by i-Gagan** [comment]
All the changes made !

**Comment by imaprincess** [comment]
Put the def BubbleSort in a class BubbleSort and rename the def in "sort", then add the def "print" in the class

**Comment by i-Gagan** [comment]
@imaprincess Finally as per your requirements !!!
But the new code is including classes + methods +Calling through objects
resulting in a lengthy code !

**Pull request merged**
