### PR TITLE
Add some Java sort algorithms

### PR DESCRIPTION
**Pull request by afilini**
All the algorithms extend an abstract class which contains a couple of useful methods.

Everything has been generalized, so that every class implementing `Comparable` can be sorted using those algorithms.

### CODE REVIEW

**Comment by afilini** [comment]
This PR is related to issue #2

**Comment by SolangeUG** [comment]
Hi @imaprincess, hi @afilini,

what happened to the abstract class SortAlgorithm ? If I'm not mistaken, I don't see it in the code base anymore... But Java classes like BubbleSort and SelectionSort still have a reference to it ? I thought it was a great abstraction for other sort classes to extend...

Thanks in advance for your help :smiley:

**Comment by imaprincess** [comment]
@SolangeUG I think someone deleted it and I didn't notice it 😭
I'll fix it asap

**Comment by SolangeUG** [comment]
@imaprincess Thank you so much for your quick reply! You're amazingly quick! :smile:

**Comment by afilini** [comment]
I created a new PR (#211) to restore the missing files. As soon as @imaprincess merges it everything should start working again!

**Comment by SolangeUG** [comment]
Thank you @afilini ! I'll also refactor my code to use your class! :smiley:

**Pull request merged**
