### PR TITLE
Fenwick tree added

### PR DESCRIPTION
**Pull request by AkshGautam**
The code written is easiest to understand and the compactness ensures that it can be easily used by competitive programmers out there since fenwick tree is frequently used for prefix sum computations in competitive programming paradigm.It saves a lot of space which a segment tree might take up.
Thanks!

### CODE REVIEW

**Comment by imaprincess** [comment]
Sadly, someone has already wrote it :c

**Comment by AkshGautam** [comment]
Damn that hurts! :(

**Comment by imaprincess** [comment]
I am sad too :c 
Maybe you can translate it in another language (Java/JS/whatever you want but Python and C/C++) c:

**Comment by AkshGautam** [comment]
unfortunately i prefer cpp,c and python,any other issue in store for me?

**Comment by imaprincess** [comment]
Mmh, can you write a segment tree in Python? I haven't opened any issue yet, but you can do it anyways c:

**Comment by AkshGautam** [comment]
i can write it in python but cpp would be perfection. @imaprincess

**Comment by imaprincess** [comment]
I already wrote it in cpp :c 
If you prefer coding in cpp, give a look at the repo: I'm pretty sure you'll find an algorithm that nobody else wrote it!

**Comment by AkshGautam** [comment]
do you need algorithm or DS.since fenwick,segment fall under DS.i could write trie in cpp for you if you need that? @imaprincess

**Comment by imaprincess** [comment]
Yes, a trie would be perfect

**Comment by AkshGautam** [comment]
Thanks,you are so nice!

**Comment by AkshGautam** [comment]
what operations do you need the trie to have? would insertion and finding if a string exists suffice or do you need some other specific functionalities? @imaprincess

**Comment by imaprincess** [comment]
Start with these functionalities, then if I'll need something else I'll write them c: 
For now it's ok if it is a "primitive" version, then we'll improve it 😉

**Comment by AkshGautam** [comment]
Basic Trie added please review PR #22 .if you need any other DS or algo/ modifications,ill be happy to help @imaprincess

**Comment by AkshGautam** [comment]
@imaprincess  do you need a heap as well?

**Pull request closed without merging**
