### PR TITLE
QuickSort in Java

### PR DESCRIPTION
**Pull request by anshul98ks123**

### CODE REVIEW

**Comment by khokharnikunj8** [comment]
@anshul98ks123 can you Explain pivot part in java algorithms further ? Remaining looks perfect.

**Comment by anshul98ks123** [comment]
i have updated the code with further explaination

**Comment by khokharnikunj8** [comment]
@imaprincess Looks fine.

**Comment by anshul98ks123** [comment]
i have made the changes and made a new PR #80

**Pull request closed without merging**
